services:
  # Веб-сервер с PHP приложением
  web:
    build: ./web
    container_name: news
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html  # Монтируем код проекта
    networks:
      app_network:
        aliases:
          - news.permaviat.ru
    environment:
      - APP_URL=http://news.permaviat.ru:8080  # Передаем URL приложению
      - SERVER_NAME=news.permaviat.ru
    restart: unless-stopped

  # База данных MySQL
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: strong_password_123
      MYSQL_DATABASE: news
      MYSQL_USER: app_user_dev
      MYSQL_PASSWORD: strong_password_123
    volumes:
      - ./db/data:/var/lib/mysql 
      - ./DefaultSQL:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306" 
    networks:
      - app_network
    command: 
      - --default-authentication-plugin=mysql_native_password 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: strong_password_123
      UPLOAD_LIMIT: 128M
      MEMORY_LIMIT: 256M
    ports:
      - "8081:80" 
    networks:
      - app_network
    depends_on:
      - db

# Общая сеть для контейнеров
networks:
  app_network:
    driver: bridge